LOC - Created file structure
Hyp-ed/hyped-2025 pull request #24
Opened 2024-10-10 17:50 UTC by misha7b

Created file structure for localisation, corect I think.

2024-10-10 17:53 UTC, davidbeechey requested changes

2024-10-10 17:53 UTC, davidbeechey commented on lib/localisation/cargo.toml
I think you need a capital "C" in the filename

2024-10-10 17:58 UTC, misha7b commented on lib/localisation/cargo.toml
lol

2024-10-10 18:59 UTC, davidbeechey approved these changes

2024-10-11 10:55 UTC, davidbeechey approved these changes

2024-10-14 17:40 UTC, kshxtij requested changes
LGTM, just rename preprocess files to not have the prefix.

2024-10-14 17:44 UTC, kshxtij approved these changes

2024-10-14 17:49 UTC, merged