HYPE-39 - Initial ADC Implementation
Hyp-ed/hyped-2025 pull request #25
Opened 2024-10-10 18:21 UTC by H00pyFr00d

Converted the `adc.hpp` from [2024](https://github.com/Hyp-ed/hyped-2024/blob/master/lib/io/adc.hpp). David and I discussed and realised that no ADC exclusive sensor was ever used last year, and so only the MUX code has ever been used

As such this is being temporarily abandoned, the work done thusfar (however minimal) is being kept here

2024-10-15 17:32 UTC, davidbeechey requested changes
A few changes are needed now because of the change in repo structure. You'll need to move the `lib/io/stm32l476rg/src/adc.rs` into `boards/stm32l476rg/src/io`. (You need to open the `boards/stm32l476rg` folder in VS Code to get IDE features from Rust Analyzer.) Not sure about the channel...

2024-10-15 17:32 UTC, davidbeechey commented on lib/io/src/adc.rs
We can't import `AnyAdcChannel` here because we don't have `embassy_stm32` in `lib/io`, so I think you'll have to implement the channel differently

2024-10-15 17:32 UTC, davidbeechey commented on lib/io/stm32l476rg/src/adc.rs
According to the [documentation](https://docs.embassy.dev/embassy-stm32/git/stm32g031c8/adc/struct.Adc.html#method.blocking_read) for `blocking_read` it returns a `u16`

2024-10-24 17:24 UTC, H00pyFr00d commented
ADC implementation which passes `cargo build`, should (in theory) work

2024-10-24 19:18 UTC, davidbeechey requested changes
Figured out the channel thing:
- `embassy_stm32::adc::Adc::new` takes in a peripheral which is the ADC on the board (there is more than one), e.g. `p.ADC1`
- Then the `AnyAdcChannel` input to `Adc::blocking_read` is a pin which implements the `AnyAdcChannel` trait for selected ADC which was passed into `new`.

Basically makes sense to rename `pin` to `channel` anyway but otherwise looks perfect. To instantiate it would be this (I've just checked that this compiles properly):
```rust
let adc = Adc::new(p.ADC1);
let hyped_adc = Stm32l476rgAdc::new(adc, p.PA0.degrade_adc());
```

Also fix typos + formatting, then mark as ready for review :)

2024-10-24 19:18 UTC, davidbeechey commented on boards/stm32l476rg/src/io/adc.rs
> +    pin: AnyAdcChannel<T>,
rename `pin` to `channel` everywhere here

2024-10-24 19:18 UTC, davidbeechey commented on boards/stm32l476rg/src/io/adc.rs
> +    /// Reading from ADC requires the peripheral pin to read from
```suggestion
    /// Read a value from the ADC channel
```

2024-10-24 19:18 UTC, davidbeechey commented on lib/io/src/adc.rs
> +// ADC trait used to abstract the ADC peripheral
```suggestion
/// ADC trait used to abstract the ADC peripheral
```
Just need a triple `/` for Rust doc

2024-10-31 20:54 UTC, davidbeechey approved these changes

2024-11-01 10:49 UTC, TomLonergan03 approved these changes

2024-11-16 12:31 UTC, merged