LOC - Implement Navigator
Hyp-ed/hyped-2025 pull request #47
Opened 2024-11-11 19:10 UTC by misha7b

Transfer navigator.cpp from the 2024 codebase.

- [ ] Think of new name.  "Localisator"?

2024-11-11 19:12 UTC, kshxtij commented
Localizer?

2025-01-23 20:53 UTC, davidbeechey requested changes
Looking good, just a few things to change and comments!

2025-01-23 20:53 UTC, davidbeechey commented on lib/localisation/src/control/localizer.rs
> +const STRIPE_WIDTH: f64 = 1.0;
would be good to add a comment with the units for these

2025-01-23 20:53 UTC, davidbeechey commented on lib/localisation/src/control/localizer.rs
> +            //TODOLater: Check unit of keyence data
what unit is this referring to?

2025-01-23 20:53 UTC, davidbeechey commented on lib/localisation/src/control/localizer.rs
> +            //TODOLater: Change state
rather than handling the logic for changing state in here, the whole `preprocessor` function could return `Result<(), PreprocessorError>` or similar in this case so that the caller can deal with it instead

2025-01-23 20:53 UTC, davidbeechey commented on lib/localisation/src/control/localizer.rs
> +            // TODOLater: Change state
likewise here

2025-01-23 20:53 UTC, davidbeechey commented on lib/localisation/src/control/localizer.rs
> +        );
if you change the return type then `iteration` will also return a `Result` type, so just pass the error up

2025-01-23 20:53 UTC, davidbeechey commented on lib/localisation/src/control/localizer.rs
> +        self.acceleration = (self.velocity - self.previous_velocity) / DELTA_T; //TODOLater: is this accurate enough?
How are you going to determine whether this is accurate enough? Is that something that needs physical testing?

2025-01-23 20:53 UTC, davidbeechey commented on lib/localisation/src/control/localizer.rs
> +        let mut accelerometer_preprocessor = AccelerometerPreprocessor::new();
Might be better to just have one instance of `AccelerometerPreprocessor` like with Keyence so it's not being constantly created

2025-01-23 20:53 UTC, davidbeechey commented on lib/localisation/src/control/localizer.rs
> +        // variance =  0.094176^2 = 0.0089 m/s^2
really good comments here

2025-01-23 20:53 UTC, davidbeechey commented on lib/localisation/src/control/localizer.rs
> +impl Localizer {
Some Rust doc `///` comments for `Localizer` and the `preprocessor` and `iteration` functions would be great

2025-01-23 20:53 UTC, davidbeechey commented on lib/localisation/src/preprocessing/optical.rs
> +    let mut magnitude: f32 = 0.0;
Is it possible to keep this generic to any number of optical flow sensors? Could take the number as a constant `NUM_OPTICAL_FLOW_SENSORS` like with accelerometers, and just have a `Vec` of length 1 if there's only one?

2025-01-23 20:53 UTC, davidbeechey commented on lib/localisation/src/control/localizer.rs
> +        let raw_accelerometer_data: RawAccelerometerData<K_NUM_ACCELEROMETERS, K_NUM_AXIS> =
Didn't spot this earlier, but we don't need `K_` prefix for `K_NUM_ACCELEROMETERS` or `K_NUM_AXIS`

2025-01-30 18:15 UTC, misha7b commented on lib/localisation/src/control/localizer.rs
> +            //TODOLater: Check unit of keyence data
If it is in metres

2025-01-30 18:39 UTC, misha7b commented on lib/localisation/src/control/localizer.rs
> +        self.acceleration = (self.velocity - self.previous_velocity) / DELTA_T; //TODOLater: is this accurate enough?
Forgot to change it back, this should have just been the accelerometer sensor value

2025-02-06 09:32 UTC, davidbeechey commented on lib/localisation/src/control/localizer.rs
> +            //TODOLater: Check unit of keyence data
Are we able to make this configurable? Ideally we'd have a constant somewhere for `KEYENCE_STRIPE_DISTANCE` so that we can change whether the posts are 1m, 1.5m, etc. apart on the fly

2025-02-09 16:26 UTC, TomLonergan03 approved these changes

2025-02-09 16:53 UTC, davidbeechey approved these changes

2025-02-09 16:54 UTC, merged