SNS: Optical Flow Sensor
Hyp-ed/hyped-2025 pull request #48
Opened 2024-11-16 12:56 UTC by SnickeyX

This implements the exact logic defined in:
https://github.com/pimoroni/pmw3901-python/blob/main/pmw3901/__init__.py 

WIP

2024-11-28 16:00 UTC, ishmis reviewed
Minor things. @prakhars0206 iirc, the optical flow sensor was not soldered properly, can you confirm if that has been fixed?

Ideally you want to get to to the stage of testing the code asap with the actual sensor.

2024-11-28 16:00 UTC, ishmis commented on lib/sensors/src/optical_flow.rs
> +            let dr = match cursor.next() {
Please explain what each of `dr`, `obs`, ... actually mean briefly.

2024-11-28 16:00 UTC, ishmis commented on lib/sensors/src/optical_flow.rs
> +                return Ok((x, y)); // Return delta x and delta y if valid
unnecessary comment

2024-11-28 16:00 UTC, ishmis commented on lib/sensors/src/optical_flow.rs
> +            sleep(Duration::from_millis(10));
make the 10 a const, `RETRY_DURATION` or similar

2024-11-28 16:00 UTC, SnickeyX commented on lib/sensors/src/optical_flow.rs
> +                Word::U8(0x00),          // Definitely a better way of doing this but for some reason i was getting syntaz errors
"syntax"

2025-01-20 16:30 UTC, davidbeechey requested changes

2025-01-20 16:30 UTC, davidbeechey commented on boards/stm32l476rg/src/io/spi.rs
The way we write IO has changed - try merging the main branch into yours (update it first). IO now have their own crates in `lib/io`. So SPI is now in `/lib/io/hyped_spi`. If there's a hellish merge conflict I can resolve it if you want :)

2025-01-24 11:31 UTC, SnickeyX reviewed
has this been tested with the sensor yet?

2025-01-24 11:31 UTC, SnickeyX commented on lib/io/src/spi.rs
> +#[derive(PartialEq)] // Derive PartialEq for Word
unnecessary comment

2025-01-24 11:31 UTC, SnickeyX commented on lib/sensors/src/optical_flow.rs
> +
empty space here and below too can be removed

2025-02-11 17:34 UTC, davidbeechey commented
Things to try next:
- 400 kHz SPI frequency
- make sure there is a sleep between power up and secret sauce
- setting rotation

2025-02-20 15:36 UTC, davidbeechey commented
Tested and working 20/20/25 :)

Main problem I think was the CS line not being used. We had additional logic errors and MSB/LSB mixup which were resolved.

Supports:
- get_motion
- set_orientation
- set_rotation

2025-02-20 15:43 UTC, davidbeechey approved these changes

2025-02-23 02:25 UTC, TomLonergan03 requested changes
doubling the number of comments lmao

2025-02-23 02:25 UTC, TomLonergan03 commented on boards/stm32l476rg/src/io.rs
is this board going to be using spi?

2025-02-23 02:25 UTC, TomLonergan03 commented on lib/io/hyped_spi/hyped_spi_derive/src/lib.rs
> +                let binding = words.iter().map(|word| *word).collect::<Vec<u8, 64>>();
```rs
let binding = words.iter().copied().collect::<Vec<u8, 64>>();
```

2025-02-23 02:25 UTC, TomLonergan03 commented on lib/io/hyped_spi/hyped_spi_derive/src/lib.rs
> +                let mut binding = data.iter().map(|word| *word).collect::<Vec<u8, 64>>();
`copied` again here

2025-02-23 02:25 UTC, TomLonergan03 commented on lib/io/hyped_spi/hyped_spi_derive/src/lib.rs
> +                            words[i] = *word;
check if `new_words` will actually fit in `words`

or is there a 64 byte limit on spi reads?

2025-02-23 02:25 UTC, TomLonergan03 commented on lib/io/hyped_spi/hyped_spi_derive/src/lib.rs
> +            fn read(&mut self, words: &mut [u8]) -> Result<(), SpiError> {
is there any way not to have out params?
prob
```rs
fn ... -> Result<Vec<u8, 64>, SpiError>
```
or 
```rs
fn ... -> Result<(Vec<u8, 64>, usize), SpiError>
```
where `usize` is the number of set bytes?

i assume you tried something like this though

2025-02-23 02:25 UTC, TomLonergan03 commented on lib/io/hyped_spi/hyped_spi_derive/src/lib.rs
> +                            data[i] = *word;
same as earlier on array sizes, on debug builds the overflow is caught but on release it'll corrupt shit/panic iirc

2025-02-23 02:25 UTC, TomLonergan03 commented on lib/sensors/src/optical_flow.rs
> +    fn get_id(&mut self) -> Result<(u8, u8), OpticalFlowError> {
why not just inline this? packing stuff into then straight back out of pairs feels bad (on vibes only so ignore if you want)

2025-02-23 02:25 UTC, TomLonergan03 commented on lib/sensors/src/optical_flow.rs
i think in general at least add a `safety` section to the docs for each function saying what the cs should be set to for each call, or better set the cs inside functions as needed (if that's possible)

for bonus points, make a wrapper class for the cs with an `impl Drop` so you automatically release CS when it goes out of scope lol

2025-02-23 02:25 UTC, TomLonergan03 commented on lib/sensors/src/optical_flow.rs
> +            let _shutter_lower = cursor.next();
if these `_...` vars are genuinely irrelevant going forwards i'd just do `cursor.skip(...)`

2025-02-23 02:25 UTC, TomLonergan03 commented on lib/sensors/src/optical_flow.rs
> +    pub async fn set_rotation(&mut self, orientation: Orientation) -> Result<(), OpticalFlowError> {
can this just be part of the constructor? i don't expect the orientation of the chip will change during the run

2025-02-23 02:25 UTC, TomLonergan03 commented on lib/sensors/src/optical_flow.rs
> +    pub async fn set_orientation(
shouldn't be `pub`

2025-02-23 02:25 UTC, TomLonergan03 commented on lib/sensors/src/optical_flow.rs
> +        self.spi.transfer_in_place(data).unwrap();
what's the difference between this and a `spi.write(...)` followed by an `spi.read(...)`

2025-02-23 02:25 UTC, TomLonergan03 commented on lib/sensors/src/optical_flow.rs
> +    async fn bulk_write(&mut self, write_data: &[(u8, u8)]) -> Result<(), OpticalFlowError> {
interesting that this seems to set and release cs for each write, that was what i thought went wrong with the c++ last year

2025-02-23 02:25 UTC, TomLonergan03 commented on lib/sensors/src/optical_flow.rs
> +        while start.elapsed() < TIMEOUT {
:+1: very nice

2025-02-23 02:27 UTC, TomLonergan03 commented on lib/sensors/src/optical_flow.rs
on second thoughts maybe this is already done, i'm a little drunk so may not have followed it properly

2025-02-23 11:49 UTC, davidbeechey commented on boards/stm32l476rg/src/io.rs
not currently

2025-02-24 14:20 UTC, davidbeechey commented on lib/sensors/src/optical_flow.rs
> +        self.spi.transfer_in_place(data).unwrap();
No difference I think

2025-02-24 14:21 UTC, davidbeechey commented on lib/sensors/src/optical_flow.rs
> +    pub async fn set_orientation(
Might want to use this over `set_rotation` maybe which is why it's `pub`, but will remove and add to the constructor anyway because I agree that makes more sense

2025-02-24 14:21 UTC, davidbeechey commented on lib/sensors/src/optical_flow.rs
> +    pub async fn set_rotation(&mut self, orientation: Orientation) -> Result<(), OpticalFlowError> {
will do

2025-02-24 14:22 UTC, davidbeechey commented on lib/sensors/src/optical_flow.rs
I think there's two options:
- we add the CS logic to `hyped_spi`
- we keep it separate and add documentation explaining what should happen and do the `impl Drop`

Not sure which is better, I don't know enough about SPI to know whether the CS behaviour is the same always

2025-02-24 22:30 UTC, davidbeechey commented on lib/sensors/src/optical_flow.rs
have added a wrapper for the CS pin that implements `Drop` :)

2025-02-27 18:11 UTC, TomLonergan03 approved these changes
looks good

2025-02-27 18:33 UTC, ishmis reviewed
minor things, looks good overall

2025-02-27 18:33 UTC, ishmis commented on lib/io/hyped_spi/hyped_spi_derive/src/lib.rs
> +                        spi::Error::Overrun => SpiError::Overrun,
would be nicer to have this mapping be one separate function used by all three `read`, `write` and `transfer_in_place`

2025-02-27 18:33 UTC, ishmis commented on lib/io/hyped_spi/src/lib.rs
> +pub use cs::*;
since there isn't much in `cs`, I would define it in-line here and then just `use hyped_spi::cs::HypedSpiCsPin` for wherever it is needed

2025-02-27 18:33 UTC, ishmis commented on lib/io/hyped_spi/src/lib.rs
> +    /// Perform a Bidirectional transfer (using DMA), i.e. an SPI transaction
i might've written this but it should just be lower-case b in `bidirectional`

2025-02-27 18:33 UTC, ishmis commented on lib/sensors/src/optical_flow.rs
> +            // OR 0x80 to the register
yes

2025-02-27 18:33 UTC, ishmis commented on lib/sensors/src/optical_flow.rs
> +// Constants
Timing Constants? (consistency w/ sensors constants)

2025-02-27 19:39 UTC, davidbeechey commented on lib/io/hyped_spi/hyped_spi_derive/src/lib.rs
> +                        spi::Error::Overrun => SpiError::Overrun,
good point, I've done this for I2C now too

2025-02-27 20:07 UTC, ishmis commented
can't approve but lgtm

2025-03-04 09:22 UTC, H-Allen approved these changes

2025-03-04 10:33 UTC, merged