INFRA - Telemetry Board
Hyp-ed/hyped-2025 pull request #5
Opened 2024-08-03 16:04 UTC by kshxtij

This pr initialises the code for the Telemetry board (as of now) which connects to the MQTT broker running on the base station and acts as a intermediary for all can messages and mqtt messages between the rest of the pod and the base station.

This PR currently contains boiler plate code to stress test the connection including a button based interrupt data sender as well as a time based task. It also handles receiving messages from the broker on subscribed topics.

sidenote: idk if infra is the tag you want on the pr

2024-10-29 11:30 UTC, davidbeechey requested changes
I've tested this by plugging the board into my router and setting the IPs for my gateway and laptop accordingly, and it worked perfectly.

All this needs now is moving all config into `lib/config`, tidying/documenting a wee bit, and deciding whether we keep the test tasks in there or not (we could have a separate bin file for running it with tests?)

2024-10-29 11:30 UTC, davidbeechey commented on boards/stm32h743zi/src/bin/telemetry.rs
> +        address: Ipv4Cidr::new(Ipv4Address::new(169, 254, 195, 61), 24),
These addresses should be in the config file

2024-10-29 11:30 UTC, davidbeechey commented on boards/stm32h743zi/src/tasks/mqtt_send_and_recv.rs
> +        .connect((Ipv4Address::new(169, 254, 195, 141), 1883))
Likewise with the broker addresses

2024-10-29 18:10 UTC, davidbeechey requested changes
Also please change the topics to some new test topics you can add to `hyped_core`

2024-10-29 21:18 UTC, davidbeechey requested changes

2024-10-29 21:18 UTC, davidbeechey commented on boards/stm32h743zi/src/tasks/mqtt_send_and_recv.rs
> +        .connect(GATEWAY_ADDRESS)
This should be called `MQTT_BROKER_ADDRESS`. I think the was Kshitij had networking configured meant that the same IP was used for both

2024-10-29 21:18 UTC, davidbeechey commented on boards/stm32h743zi/src/bin/telemetry.rs
> +        address: BROKER_CIDR,
`BROKER_CIDR` I think is actually the static IP that the board will have, so should be called `BOARD_STATIC_IP` or something instead

2024-10-31 20:46 UTC, davidbeechey approved these changes
Looks good, obviously the main function will be changing once CAN is finished to code that will relay messages between CAN and MQTT. Until then I'm happy having the test code in there instead

2024-10-31 20:51 UTC, platinumxy approved these changes

2024-10-31 20:56 UTC, kshxtij reviewed
LGTM, just unsure about the clock values but we can swap that if we run into problems to match the stm32h7 example from embassy-rs

2024-10-31 20:56 UTC, kshxtij commented on boards/stm32h743zi/src/bin/telemetry.rs
> +        config.rcc.ahb_pre = AHBPrescaler::DIV1;
https://github.com/embassy-rs/embassy/blob/f319f1bc1b36cd6c7860391e49083ee64c079547/examples/stm32h7/src/bin/eth.rs#L33 ?? Not sure about each individual clock value

2024-11-03 11:54 UTC, merged