MLC - CanOpen
Hyp-ed/hyped-2025 pull request #50
Opened 2024-11-16 15:42 UTC by jpfbastos

2025-02-09 18:43 UTC, davidbeechey requested changes
Looking good! Have made a few comments, but apart from that some good Rust doc comments would be great.

I'm tempted to say we should split this into CanOpen and motor controller stuff - let me know what you think :)

2025-02-09 18:43 UTC, davidbeechey commented on lib/motors/src/can_open_message.rs
> +    pub const SET_FREQUENCY: CanOpenMessage = CanOpenMessage {
possibly worth a comment explaining that `data` will be overwritten somewhere else

2025-02-09 18:43 UTC, davidbeechey commented on lib/motors/src/can_processor.rs
should this be called `can_open_processor`?

2025-02-09 22:51 UTC, jpfbastos commented
> Looking good! Have made a few comments, but apart from that some good Rust doc comments would be great.
> 
> I'm tempted to say we should split this into CanOpen and motor controller stuff - let me know what you think :)

yeah fair enough - i kinda wung it, and then forgot to a) add RustDoc comments and b) split the PRs

2025-02-14 11:54 UTC, davidbeechey approved these changes
Looks good!

2025-02-14 12:32 UTC, TomLonergan03 requested changes

2025-02-14 12:32 UTC, TomLonergan03 commented on lib/motors/src/can_open_processor.rs
> +            data: u32::from(frame.data[4])
```rs
u32::from_le_bytes([frame.data[4], frame.data[5], frame.data[6], frame.data[7]])
```

(you can also do something like
```rs
let message_data = msg.data.to_le_bytes();
data.split_at_mut(4).1.copy_from_slice(&message_data);
```
for the other way round, but that's kinda ugly imo)

2025-02-14 12:32 UTC, TomLonergan03 commented on lib/motors/src/can_open_processor.rs
> +pub enum MessagesEnum {
just call it `Messages`

2025-02-14 12:42 UTC, TomLonergan03 commented on lib/motors/src/can_open_processor.rs
another thing i just thought of, write a test that asserts `From<CanOpenMessage>` and `From<CanFrame>` are actually inverses of each other

2025-02-15 12:46 UTC, jpfbastos commented on lib/motors/src/can_open_processor.rs
> +            data: u32::from(frame.data[4])
I changed for the first one, but I think I might keep what I have for the other way round, bc I think it's more readable (thanks for letting me know tho)

2025-02-15 14:55 UTC, TomLonergan03 approved these changes

2025-02-15 15:05 UTC, merged