SNS - High Power Relay
Hyp-ed/hyped-2025 pull request #55
Opened 2024-11-25 18:42 UTC by Hiatus44I

2024-12-02 20:32 UTC, davidbeechey requested changes

2024-12-02 20:32 UTC, davidbeechey commented on lib/io/src/gpio.rs
> +}
We actually need to separate the input and output GPIO pins, like in PR #40 [lib/io/src/gpio.rs](https://github.com/Hyp-ed/hyped-2025/pull/40/files#diff-d5bdff5232fdae77ea3da505b80e8189de7dba771accf55b4b245a54d757416e).

2024-12-02 20:32 UTC, davidbeechey commented on lib/control/src/hp_relay.rs
> +
remove

2024-12-02 20:32 UTC, davidbeechey commented on lib/control/src/hp_relay.rs
> +pub struct HighPowerRelay<T: HypedGpioPin> {
Add a Rust doc comment here explaining what this does

2025-01-21 18:35 UTC, davidbeechey approved these changes

2025-01-21 20:04 UTC, TomLonergan03 approved these changes

2025-01-23 17:11 UTC, jpfbastos approved these changes

2025-01-23 20:54 UTC, merged